chore: merge `v2-dev-1` into `v2-dev-2` (#577)
### What Changed?
`incredible-squaring` integration test is failling with
```
---- incredible_squaring::test_incredible_squaring stdout ----

thread 'incredible_squaring::test_incredible_squaring' panicked at tests/integration/src/generic_avs.rs:340:26:
called `Result::unwrap()` on an `Err` value: TaskManagerError(TransportError(ErrorResp(ErrorPayload { code: -32003, message: "nonce too low", data: None })))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
To fix this, you can change the deployer address since aggregator and
task spammer use the same pk

### Reviewer Checklist

- [ ] New features are tested and documented
- [ ] PR updates the changelog with a description of changes
- [ ] PR has one of the `changelog-X` labels (if applies)
- [ ] Code deprecates any old functionality before removing it

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Pablo Deymonnaz <deymonnaz@gmail.com>
Co-authored-by: Pablo Deymonnaz <pdeymon@fi.uba.ar>
Co-authored-by: Tomás Grüner <47506558+MegaRedHand@users.noreply.github.com>
Co-authored-by: supernovahs <91280922+supernovahs@users.noreply.github.com>
Co-authored-by: supernovahs <supernovahs@proton.me>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Maximo Palopoli <96491141+maximopalopoli@users.noreply.github.com>